# Generated by Django 2.2.1 on 2024-03-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_dapartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dapartment',
            old_name='caption',
            new_name='title',
        ),
    ]
